#!/bin/bash
# -*- coding: utf-8 -*-
import PIL.Image
from tkinter import*
from tkinter.filedialog import *

def Stega():
    global filepath,filepath2
    im_pass = PIL.Image.open(filepath)
    im_cont = PIL.Image.open(filepath2)
    value_test = im_pass.getpixel((0,0))# form RGBA ==> rouge vert bleu Alpha(= Opacity)
    value_test2 = im_cont.getpixel((0,0))
    im_pass_size = im_pass.size
    im_cont_size = im_cont.size 
    RGB_pass = []
    RGB_cont = []
    print(im_pass_size)
    for i in value_test:
        tmp = str(format(i, "08b"))
        tmp2 = tmp[5:]
        RGB_pass.append(tmp2)
    for j in value_test2:
        tmp = str(format(j, "08b"))
        tmp2 = tmp[3:]
        RGB_cont.append(tmp2)
    RGB_final = []
    RGB_final.append(RGB_cont[0] + RGB_pass[0])
    RGB_final.append(RGB_cont[1] + RGB_pass[1])
    RGB_final.append(RGB_cont[2] + RGB_pass[2])
    RGB_decimal = []
    for a in range(0,3):
        RGB_decimal.append(int(RGB_final[a],2))
    tuple_RGB = (RGB_decimal[0],RGB_decimal[1],RGB_decimal[-1])
    im_cont.putpixel((0,0),tuple_RGB)
    im_cont.show()
    
def valid_imgpass():
    global fenetre_2,filepath,check_selected,Select_img
    fenetre_2.destroy()
    selected_img_pass_label = Label(fenetre_1,text="Img pass selected").place(relx= 0.5, rely= 0.25,anchor=CENTER)
    Select_img.destroy()
    check_selected += 1
    if check_selected == 2:
        Stega()
    else:
        pass
def valid_imgcont():
    global fenetre_3,filepath2,check_selected,Select_img2
    fenetre_3.destroy()
    selected_img_cont_label = Label(fenetre_1,text="Img cont selected").place(relx= 0.5, rely= 0.55,anchor=CENTER)
    Select_img2.destroy()
    check_selected += 1
    if check_selected == 2:
        Stega()
    else:
        pass
def img_cont():
    global photo2,fenetre_3,filepath2
    filepath2 = askopenfilename(title="Choisissez l'image",filetypes=[('png files','*.png'),('jpg files','*.jpg')])
    if len(filepath2) <= 1:
        pass
    else:
        photo2 = PhotoImage(file=filepath2)
        #affiche l'image conteneur dans une nouvelle fentre
        var1= int(photo2.height())
        var2 = var1 + 30
        var3 = var1 + 15
        fenetre_3 = Toplevel(fenetre_1)
        Image_canvas2 = Canvas(fenetre_3, width=photo2.width(), height=photo2.height())
        Image_canvas2.create_image(0,0,anchor=NW,image=photo2)
        fenetre_3.minsize(photo2.width(),var2)
        fenetre_3.maxsize(photo2.width(),var2)
        fenetre_3.title("Image Hidder {}".format(filepath2))
        boutton_valid_cont = Button(fenetre_3,text="Valider", command = valid_imgcont, width= photo2.width()).place(relx= 0.5,y= var3,anchor=CENTER)
        Image_canvas2.place(relx=0, rely= 0,anchor=NW)

def img_pass():
    global photo,fenetre_2,filepath
    filepath = askopenfilename(title="Choisissez l'image",filetypes=[('png files','*.png'),('jpg files','*.jpg')])
    if len(filepath) <= 1:
        pass
    else:
        photo = PhotoImage(file=filepath)
        #affiche l'image a décripter dans une nouvelle fentre
        fenetre_2 = Toplevel(fenetre_1)
        var1= int(photo.height())
        var2 = var1 + 30
        var3 = var1 + 15
        Image_canvas = Canvas(fenetre_2, width=photo.width(), height=var2)
        Image_canvas.create_image(0,0,anchor=NW,image=photo)
        fenetre_2.minsize(photo.width(),var2)
        fenetre_2.maxsize(photo.width(),var2)
        fenetre_2.title("Image Hidded {}".format(filepath))
        boutton_valid_pass = Button(fenetre_2,text="Valider", command = valid_imgpass, width= photo.width()).place(relx= 0.5,y= var3,anchor=CENTER)
        Image_canvas.place(relx=0, rely= 0,anchor=NW)

def dimention_fen():
    global ecran_x
    #dimension et emplacement de la fentre au lancement du programme
    fenetre_1.geometry("800x600+0+0")
    ecran_x = fenetre_1.winfo_screenwidth()
    ecran_y = fenetre_1.winfo_screenheight()
    fenetre_x = 800
    fenetre_y = 600
    posX = (ecran_x // 2) - (fenetre_x // 2)
    posY = (ecran_y // 2) - (fenetre_y // 2)
    geo =("{}x{}+{}+{}".format(fenetre_x,fenetre_y,posX,posY))
    fenetre_1.geometry(geo)
    fenetre_1.minsize(650,400)#taille min en x*y

global ecran_x,check_selected
check_selected = 0
fenetre_1 = Tk()

fenetre_1.title("Stéganoraphie by Rida and Yasin")

dimention_fen()

#afficher l'image pour décripter
Select_img = Button(fenetre_1,text="selectionnez une image pass",command = img_pass)
Select_img.place(relx=0.5, rely=0.3,height= 50,width= 300, anchor=CENTER)

#afficher l'image conteneur
Select_img2 = Button(fenetre_1,text="selectionnez une image cont",command = img_cont)
Select_img2.place(relx=0.5, rely=0.5,height= 50,width= 300, anchor=CENTER)

#afficher une ligne de séparation
x1= ecran_x * 0.005
x2= ecran_x * 0.9
y1= 3
y2= 2
ligne_sepa = Canvas(fenetre_1,height = 10, width = 750)
ligne_sepa.create_line(x1,y1,x2,y2,width=5,fill='grey')
ligne_sepa.place(relx=0.5, rely=0.4, anchor=CENTER)

#Bouton quitter
boutton_quit = Button(fenetre_1,text="Quitter", command = fenetre_1.destroy).place(relx=0.85, rely=0.85,width= 100, height= 50, anchor=CENTER)

fenetre_1.mainloop()
